server:
  port: 11000
  tomcat: 
    basedir: /usr/local/yogaserver/yoga
    accesslog: 
      enabled: true
logging: 
  path: /usr/local/yogaserver/yoga/log
  file:  yoga.log
spring:
  data:
    mongodb:
      host: 192.168.1.2
      port: 27017
      database: yoga
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1