server:
  port: 11000
  tomcat: 
    basedir: /usr/local/yogaserver/yoga
    accesslog: 
      enabled: true
logging: 
  path: /usr/local/yogaserver/yoga/log
  file:  yoga.log

spring:
  application:
    name: yoga
  http:
    converters:
      preferred-json-mapper: fastjson
  cloud:
    config:
      label: master
      profile: default
      uri: http://localhost:16000/
      failFast: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: yoga
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1