server:
  port: 10000
  tomcat: 
    basedir: ~/usr/local/yogaserver/usercenter
    accesslog: 
      enabled: true
logging: 
  path: /usr/local/yogaserver/usercenter/log
  file:  usercenter.log
spring:
  application:
    name: user
  cloud:
    config:
      label: master
      profile: default
      uri: http://localhost:16000/
      failFast: true
  data:
    mongodb:
      # host: 172.31.27.148
      host: 127.0.0.1
      port: 27017
      database: yoga

  redis:
    # host: 172.31.27.148
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  social:
    facebook:
      app-id: 468287860237491
      app-secret: d00619cdd2916c64786909b99194796f